import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../shared/styles/globals.css'
import Navbar from '@/shared/components/navbar/navbar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'MENTANA',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			
			<body className={inter.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
