import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../shared/styles/globals.css'
import '../config/firebase-config'

import Navbar from '@/shared/components/navbar/navbar'
import Footer from '@/shared/components/Footer/footer'

import GlobalProvider from '@/shared/context/global'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'MENTANA',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	
	return (
		<GlobalProvider>
			<html lang="en">
				<body className={`${inter.className} flex flex-col min-h-screen`}>
					<Navbar />
					<main className="flex-grow">{children}</main>
					<Footer />
				</body>
			</html>
		</GlobalProvider>

	)
}